In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(np.mean(arr))
print(np.sum(arr))

[1 2 3 4 5]
3.0
15


In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))
print("Biggest:", np.max(arr))
print("Smallest:", np.min(arr))


Array: [10 20 30 40 50]
Sum: 150
Average: 30.0
Biggest: 50
Smallest: 10


In [3]:
#Math operations
print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

Sum: 150
Average: 30.0
Max: 50
Min: 10


In [4]:
#2D array 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix:\n", matrix)


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Range of numbers
r = np.arange(1, 11)
print("Range 1-10:", r)


Range 1-10: [ 1  2  3  4  5  6  7  8  9 10]


In [6]:
a=10
print(a)

10


In [7]:
b=78
print(b)

78
